### ISSUE TITLE
I am extremely confused

### ISSUE THREAD

**Issue by YodaLightsabr** [cursorsdottsx/express#1]
How can you have a webserver on the front end?

**Comment by k-tten** [comment]
@YodaLightsabr it's not a webserver it's client side routing. Instead of having a server feed you HTML every time you navigate the site, the site itself has all the HTML and uses JavaScript to display different pages based on the current URL.

There are two techniques that can be used to do this: using a hash router and window hashchange event, and using history.pushState with window popstate event.
